### ISSUE TITLE
Android MQTT: Crashing for devices with SDK 23

### ISSUE THREAD

**Issue by tessmerandre** [hivemq/hivemq-mqtt-client#608]
## 🐛 Bug Report

MQTT is not working for SDK level 23 since we updated Java to 17 on our Android app.

It throws a bunch of info logs to the logcat, and then it crashes on the `.callback` with the following exception:
`java.lang.NoClassDefFoundError: com.hivemq.client.internal.mqtt.c`

<img width="1101" alt="Screenshot 2023-12-14 at 11 53 28" src="https://github.com/hivemq/hivemq-mqtt-client/assets/41590665/8dceeec0-c8e2-4ce4-b3bf-ead3dc47fdf2">

![image](https://github.com/hivemq/hivemq-mqtt-client/assets/41590665/251e9df1-6caa-4694-8db2-79a84631dc73)

## 🔬 How To Reproduce

1. Set the JAVA to 17
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
}
```
2. Run the app on Android SDK level 23

### Code sample

All dependencies are set, including Retrofix:
```
classpath "com.github.sgtsilvio.gradle:android-retrofix:${Versions.retrofix}"

implementation Libs.mqtt
implementation Libs.retroStreams
implementation Libs.retroFuture
```

**Comment by tessmerandre** [comment]
Added core library desugaring to the app and seems to be fixed.
